name: Corretor de Exercícios 2º BI

on:
  push:
  workflow_dispatch:

jobs:
  ex01-primeira-pagina-html:
    name: ex02-personalizando-sua-primeira-pagina-react
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula02-primeira-pagina-com-react-e-conhecendo-o-jsx
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test